### ISSUE TITLE
feat(navigation): mobile navigation bar, responsive support

### ISSUE THREAD

**Issue by niyasrad** [niyasrad/Qreate#1]
## Feature Request
- The Qreate application would have a lot of accessibility over the dashboard, called Qreateboard
- It requires a mobile navigation bar, just like the desktop ones.

## Description
- The mobile navigation bar is supposed to be displayed over a media query of `900-990px`
- It can be closed, or opened upon a button click.
- The current `sign-out` model could be added with an `.svg` which suits the purpose.

**Comment by Vaish24navi** [comment]
Closed with PR #3
