### ISSUE TITLE
fix(backend): patch for several found issues

### ISSUE THREAD

**Issue by Vaish24navi** [niyasrad/Qreate#7]
## Description
- Currently, the `init_middlewares()` function which sets up `CORS` is not being used in the application.
- The `on_startup` event, does not confirm the connectivity between the server and `MongoDB`. 
- The attached database client `app.db` is not used throughout the current API setup, which requires a discussion, and refactor.
- The `authenticate_user` middleware does not work as intended, because of a payload mismatch, and needs to be fixed.
- The responses for the API have to be streamlined into a `data` JSON object, which can be read easier by the frontend.
- Currently, the `status_code`s for all the APIs are not being used, and needs to be addressed.
- An `authenticate/check` API is very fundamental for the frontend to understand the brand's login, and is currently missing.
- `ResponseModel` prefixed/suffixed models are not in use, and therefore have to be removed.
- The `timedelta` for access token is short, and therefore needs to be extended.
- The `not_authorised` function isn't working as intended and needs to be fixed.

**Comment by niyasrad** [comment]
Worked out with PR #8 
Great work!
